#pragma once
//screen dimensions
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MOVEMENTSPEED 100.0f
#define GRAVITY 260.0f
#define JUMP_FORCE_DECRECEMENT 440.0f
#define INITIAL_JUMP_FORCE 600.0f
#define INITIAL_JUMP_FORCE_SMALL 400.0f
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SHAKE_DURATION 0.25f
#define INJURED_TIME 2.5f
#define KOOPA_SPEED 96.0f
#define KOOPA_SPAWN_TIME 5.0f